spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true


cloudinary:
  cloud-name: dfths157i
  api-key: 311619478275982
  api-secret: eZ-kOf7Xd1z5O7Jtb2x7PsH5yok

security:
  jwt:
    secret: WW91IHJlYWxpemUgeW91J3JlIG5vdCBhbG9uZSBhcyB5b3Ugc2l0IGluIHlvdXIgYmVkcm9vbSBtYXNzYWdpbmcgeW91ciBjYWx2ZXMgYWZ0ZXIgYSBsb25nIGRheSBvZiBwbGF5aW5nIHR1Zy1vZi13YXIgd2l0aCBHcmFuZHBhIEpvZSBpbiB0aGUgaG9zcGl0YWwu
    expiration: 3600000
  refreshToken:
    expiration: 86400000

resend:
  api-key: re_ZTH91kCQ_HCgyqfnTmTMsDpMQASQLvHfX
  from-email: onboarding@resend.dev